[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
autocmd FileType go :highlight goErr cterm=bold ctermfg=214
autocmd FileType go :match goErr /\<err\>/
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
" 保存時に必要なimportを自動的に挿入
let g:go_fmt_command = "goimports"
" LSPに任せる機能をOFFにする
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
'''

# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = ['vue']
# hook_add = '''
# let g:vue_pre_processors = 'detect_on_enter'
# '''

[[plugins]]
repo = 'leafoftree/vim-vue-plugin'
on_ft = ['vue']
hook_add = '''
let g:vim_vue_plugin_highlight_vue_attr = 1
let g:vim_vue_plugin_use_sass = 1
let g:vim_vue_plugin_use_typescript = 1
let g:vim_vue_plugin_use_pug = 0
nnoremap <silent> <buffer> [[ :call search('^<\(template\<Bar>script\<Bar>style\)', 'bW')<CR>
nnoremap <silent> <buffer> ]] :call search('^<\(template\<Bar>script\<Bar>style\)', 'W')<CR>
nnoremap <silent> <buffer> [] :call search('^</\(template\<Bar>script\<Bar>style\)', 'bW')<CR>
nnoremap <silent> <buffer> ][ :call search('^</\(template\<Bar>script\<Bar>style\)', 'W')<CR>
'''

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

[[plugins]] # jsonでダブルクォートが非表示になるのを解消
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = '''
augroup FiletypeGroup
    autocmd!
    " .ts is a Typescript file
    au BufNewFile,BufRead *.ts set filetype=typescript
augroup END
'''

################
### Markdown ###
################
# quote内のプログラムをシンタックスハイライトする
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

# リッチマークダウン
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'cd app & yarn install'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
################

[[plugins]]
repo = "hashivim/vim-terraform"
on_ft = ['terraform', 'tf', 'tfvars', 'tfstate', 'hcl']
hook_add = '''
let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'miyanokomiya/key-seeker.nvim'
on_cmd = ['KeySeekerClip', 'KeySeekerDig']
hook_add = '''
nnoremap <silent> <Space>s :KeySeekerClip<CR>
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue', 'xml', 'svg', 'javascript', 'typescript']

[[plugins]]
repo = 'andys8/vim-elm-syntax'
on_ft = ['elm']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'miyanokomiya/konbu.nvim'
on_cmd = ['KonbuP']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'burner/vim-svelte'
on_ft = ['svelte']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']
