[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
autocmd FileType go :highlight goErr cterm=bold ctermfg=214
autocmd FileType go :match goErr /\<err\>/
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
" 保存時に必要なimportを自動的に挿入
let g:go_fmt_command = "goimports"
" LSPに任せる機能をOFFにする
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
let g:vue_pre_processors = 'detect_on_enter'
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'cd app & yarn install'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue', 'xml', 'svg', 'javascript', 'typescript', 'svelte']
hook_add = '''
let g:user_emmet_leader_key='<C-y>'
let g:user_emmet_mode = 'iv'
'''

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'burner/vim-svelte'
on_ft = ['svelte']

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = 'source ~/dotfiles/treesitter-settings.lua'
