[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
autocmd FileType go :highlight goErr cterm=bold ctermfg=214
autocmd FileType go :match goErr /\<err\>/
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
" 保存時に必要なimportを自動的に挿入
let g:go_fmt_command = "goimports"
" LSPに任せる機能をOFFにする
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
hook_add = '''
map <C-n> :NERDTreeToggle<CR>
let NERDTreeShowHidden = 1
'''

[[plugins]] # jsonでダブルクォートが非表示になるのを解消
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = '''
augroup FiletypeGroup
    autocmd!
    " .ts is a Typescript file
    au BufNewFile,BufRead *.ts set filetype=typescript
augroup END
'''

################
### Markdown ###
################
# quote内のプログラムをシンタックスハイライトする
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

# 編集中のMarkdownファイルのプレビューを作成する
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']

# プレビューをブラウザで開いてくれる
# :PrevimOpen
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']
################

[[plugins]]
repo = "hashivim/vim-terraform"
on_ft = ['tf']
hook_add = '''
let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'miyanokomiya/key-seeker.nvim'
on_cmd = ['KeySeekerClip', 'KeySeekerDig']
hook_add = '''
nnoremap <silent> <Space>s :KeySeekerClip<CR>
'''
